# Basic Information
title: Yulong Ye
position: Ph.D. Student
affiliation: University of Birmingham
affiliation_link: https://www.birmingham.ac.uk/
email: yxy382@student.bham.ac.uk

# Search Engine Optimization (SEO)
keywords: yulong ye, ye yulong, yulongye, software configuration tuning, evolutionary computation
canonical: https://yulong-ye.github.io/
description: Yulong Ye is a Ph.D. student at the University of Birmingham. His research focuses on software configuration tuning and evolutionary computation.

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?hl=zh-CN&user=dRAn7W4AAAAJ
cv_link:
github_link:
linkedin:
twitter:

# Images 
avatar: ./assets/img/Elon.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote:
footnote_link:

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
